version: "3.4"

services:
  api:
    build:
      context: .
      target: development
    env_file:
      - ./.env.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9090:9090
    command: npm run dev







