version: '3.4'

services:
    api:
        build:
            context: .
            target: development
        env_file:
            - ./.env.dev
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 9090:9090
        command: npm run dev
        depends_on:
            - mongodb
        networks:
            - devnetwork

    mongodb:
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./mongo-init/dist/bundle.js:/docker-entrypoint-initdb.d/bundle.js:ro
            - ./mongo-init/data/mongo:/data/db
        networks:
            - devnetwork

networks:
    devnetwork:
        driver: bridge
